import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

clr.AddReference('RevitAPI')
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference('RevitServices')
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

clr.AddReference('RevitNodes')
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

doc = DocumentManager.Instance.CurrentDBDocument

ArrayCurves = IN[0]
floorType = UnwrapElement(IN[1])
levels = UnwrapElement(IN[2])
bool = IN[3]


curvelist = []
out = []

bip = BuiltInParameter.FLOOR_HEIGHTABOVELEVEL_PARAM

for i in ArrayCurves:
	curveArray = CurveArray()
	for j in i:
		curveArray.Append(j.ToRevitType())
	curvelist.Add(curveArray)

for i in levels:
	for j in curvelist:
		TransactionManager.Instance.EnsureInTransaction(doc)
		newFloor = doc.Create.NewFloor(j, floorType, i, bool)
		TransactionManager.Instance.TransactionTaskDone()

OUT = newFloor
